### ISSUE TITLE
callsdk会和以前接入的im有消息 冲突啊

### ISSUE THREAD

**Issue by arthur20150522** [zhaoyang21cn/CallSDK_Android_Demo#11]
那些信令不能自己删除吗。。。。
会出现在IM的聊天列表耶。。。是我少配置了什么吗？
麻烦帮忙解决下。。

**Comment by xkazer** [comment]
可以先自行过滤下，获取TIMElement的getExt，判断如果是我们的标识"CallNotification"，就表示是内部信令，后续版本我们会优化这一块，如果是信令，自行删除

**Comment by arthur20150522** [comment]
好的，谢谢，因为公司的ios版本是自动删除的，我以为是我配置没有弄好，麻烦你们后续更新下这个哦

**Comment by arthur20150522** [comment]
额，我刚刚去试了，customElem.getExt()出来是空的。。。。你们确定有放这个标识吗？

**Comment by arthur20150522** [comment]
还有一个问题是，接收消息有总的接收的地方进行删除处理，可是发出的是callsdk内部发出的，外部没法监听，那些自己发出的信令都出现在了聊天列表里了。。。。。是否能加入一个总的消息发出监听一类的接口或者回调。

**Comment by xkazer** [comment]
监听消息如果直接使用RoomOption中的回调是可以收到所有消息的，如果使用CallOption中就是过滤信令后消息

**Comment by songwj1989** [comment]
你好，我这边也遇到了这样的问题。之前ok的，版本变成1.0.20后，发起请求后，普通会话列表出现了和对方的会话（接收方没有）。
    compile 'com.tencent.callsdk:callsdk:1.0.20'
    compile 'com.tencent.livesdk:livesdk:1.1.1'
    compile 'com.tencent.ilivesdk:ilivesdk:1.5.0'
    compile 'com.tencent.ilivefilter:ilivefilter:1.1.12'

**Comment by edison-xiao** [comment]
callsdk 和 云通信IM 没办法集成到一块？一堆冲突怎么解决？

**Comment by xkazer** [comment]
@edison-xiao callsdk内部已经集成了imsdk(2.5.4)，可以直接使用imsdk的功能，不需要另外集成imsdk

**Comment by edison-xiao** [comment]
callsdk 支持 v3.1.0吗？

**Comment by wangjian161** [comment]
@edison-xiao imsdk和callsdk的冲突解决了么，请问是怎么解决的呢？

**Comment by xkazer** [comment]
callsdk依赖的ilivesdk内部集成了imsdk 2.5.x，推荐是直接使用内部集成的版本，无需额外集成imsdk
