### ISSUE TITLE
最新版本com.tencent.callsdk:callsdk:1.0.13 会出现退出重进，登录失败

### ISSUE THREAD

**Issue by arthur20150522** [zhaoyang21cn/CallSDK_Android_Demo#13]
最新版本com.tencent.callsdk:callsdk:1.0.13 会出现退出重进，登录失败。
第一次登录是没有什么问题的，第二次登录发现不能正常登录了。
发现是IM已经登录成功，但是createAvContext的时候返回了NUll，所以回调了登录失败
回退到com.tencent.callsdk:callsdk:1.0.12版本就没有问题，麻烦排查下，需要什么数据请联系我。

**Comment by xkazer** [comment]
登录这一块的逻辑实现在iLiveSDK而不是Callsdk，麻烦确认一下iLiveSDK的版本，并提供一份iLiveSDK的日志，可以发我邮箱: xkazerzhang@tencent.com。感谢您的反馈

**Comment by arthur20150522** [comment]
版本都是最新的
    compile 'com.tencent.ilivesdk:ilivesdk:1.3.1'
    compile 'com.tencent.callsdk:callsdk:1.0.10'

我用你们的demo，替换成最新的sdk试试看，有错误发日志给你们。

**Comment by arthur20150522** [comment]
错误日志发过去了，请查收下，我的邮箱是640051282@qq.com
