### ISSUE TITLE
向对方发起视频聊天时，如何判断对方是否在线

### ISSUE THREAD

**Issue by abner-wu** [zhaoyang21cn/CallSDK_Android_Demo#18]
有两个问题想请教一下：
1、向对方发起视频聊天时，如何判断对方是否在线？如果对方不在线，需要在UI提示用户对方不在线。
2、在对方手机上onNewIncomingCall回调时，怎么判断视频发起方是否在线？如果发起方不在线了，就不需要弹出来电的UI界面了，只需记录一下就可以了。

**Comment by xkazer** [comment]
目前sdk不支持状态返馈，需要业务层补充这个逻辑
