### ISSUE TITLE
呼叫重新接收

### ISSUE THREAD

**Issue by songwj1989** [zhaoyang21cn/CallSDK_Android_Demo#2]
当接收方卸载重装apk或kill apk进程后，重启app时会再次接收到呼叫，即使这个呼叫已经被拒绝或挂断

**Comment by songwj1989** [comment]
如果可以的话这个sdk最好加入这个优化：发起呼叫后，发起方remove这个message；接收方接收到message后remove该条message。

**Comment by xkazer** [comment]
在发起呼叫时的ILVCallOption中的setOnlineCall配置，开启这个配置(在线才能收到消息)后，应该是满足你需求的，而且这里的来电都是有时间戳的，可以上层自己做这个过滤

**Comment by songwj1989** [comment]
好的  我试一下，麻烦你了




------------------ 原始邮件 ------------------
发件人: "xkazer";<notifications@github.com>;
发送时间: 2016年12月19日(星期一) 上午10:01
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "宋伟建"<784580117@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 呼叫重新接收 (#2)




在发起呼叫时的ILVCallOption中的setOnlineCall配置，开启这个配置(在线才能收到消息)后，应该是满足你需求的，而且这里的来电都是有时间戳的，可以上层自己做这个过滤

**Comment by xkazer** [comment]
在没有开启setOnlineCall配置时，卸载重装会再次接收这个问题，我们会在下一版本中优化，感谢您的支持
