### ISSUE TITLE
点击注册后没反应, 帐号密码都用的手机号

### ISSUE THREAD

**Issue by jinloong** [zhaoyang21cn/CallSDK_Android_Demo#21]

**Comment by wangcc0909** [comment]
同问

**Comment by ZhiruiLi** [comment]
请下载最新版本的工程，旧版的 Demo 在注册帐号如果不符合要求时不会有任何提示，新版本会显示提示

**Comment by wangcc0909** [comment]
我用的就是跳转之后的callSDK的demo,还有新版的吗,我在你的仓库中没有看到




------------------ 原始邮件 ------------------
发件人: "Zhirui Li";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 下午5:20
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "Android开发"<1079793182@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 点击注册后没反应, 帐号密码都用的手机号 (#21)




请下载最新版本的工程，旧版的 Demo 在注册帐号如果不符合要求时不会有任何提示，新版本会显示提示

**Comment by ZhiruiLi** [comment]
当前这个就是新版啊，现在如果用手机号注册的话应该会提示“用户名为 4 ~ 24 个字符，不能为纯数字”吧？

**Comment by wangcc0909** [comment]
是的,就是提示这个
------------------ 原始邮件 ------------------
发件人: "Zhirui Li";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 下午5:32
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "Android开发"<1079793182@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 点击注册后没反应, 帐号密码都用的手机号 (#21)




当前这个就是新版啊，现在如果用手机号注册的话应该会提示“用户名为 4 ~ 24 个字符，不能为纯数字”吧？

**Comment by ZhiruiLi** [comment]
所以就是不可以直接用手机号注册呀，随便加个字母进去吧

**Comment by wangcc0909** [comment]
我加了,无论是前面还是后面我都试过了,但是10秒之后提示TLSSDK|-1000的错误,请检查,是需要在代码中替换什么?




------------------ 原始邮件 ------------------
发件人: "Zhirui Li";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 下午5:35
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "Android开发"<1079793182@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 点击注册后没反应, 帐号密码都用的手机号 (#21)




所以就是不可以直接用手机号注册呀，随便加个字母进去吧

**Comment by ZhiruiLi** [comment]
可以发一下用于注册的用户名和密码吗？我这边没有遇到这样的情况

**Comment by wangcc0909** [comment]
账户w15279832376  密码:15279832376 
我试过好几遍都是这个情况


------------------ 原始邮件 ------------------
发件人: "Zhirui Li";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 下午5:46
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "Android开发"<1079793182@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 点击注册后没反应, 帐号密码都用的手机号 (#21)




可以发一下用于注册的用户名和密码吗？我这边没有遇到这样的情况

**Comment by wangcc0909** [comment]
你好,你能发个你注册好的账号给我吗?


------------------ 原始邮件 ------------------
发件人: "Zhirui Li";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 下午5:46
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "Android开发"<1079793182@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 点击注册后没反应, 帐号密码都用的手机号 (#21)




可以发一下用于注册的用户名和密码吗？我这边没有遇到这样的情况

**Comment by ZhiruiLi** [comment]
帐号：w15279832376 密码：15279832376 现在应该可以用了，试试

**Comment by wangcc0909** [comment]
谢谢你了


------------------ 原始邮件 ------------------
发件人: "Zhirui Li";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 晚上9:05
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "Android开发"<1079793182@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 点击注册后没反应, 帐号密码都用的手机号 (#21)




帐号：w15279832376 密码：15279832376 现在应该可以用了，试试

**Comment by wangcc0909** [comment]
你好！我这里想问一下，，我使用的CallSDK，三个人进入同一个房间还是显示的两个人的视频窗口，这是怎么回事？


------------------ 原始邮件 ------------------
发件人: "Zhirui Li";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 晚上9:05
收件人: "zhaoyang21cn/CallSDK_Android_Demo"<CallSDK_Android_Demo@noreply.github.com>; 
抄送: "Android开发"<1079793182@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhaoyang21cn/CallSDK_Android_Demo] 点击注册后没反应, 帐号密码都用的手机号 (#21)




帐号：w15279832376 密码：15279832376 现在应该可以用了，试试

**Comment by xkazer** [comment]
如果大家都看不到其中一个人的画面，可以确认下此人的摄像头权限，也可以结合[日志](https://github.com/zhaoyang21cn/CallSDK_Android_Demo/blob/master/doc/mainlog.md)看看是否打开摄像头失败
