### ISSUE TITLE
IM3.1.0 版本怎么集成 CallSDK？

### ISSUE THREAD

**Issue by edison-xiao** [zhaoyang21cn/CallSDK_Android_Demo#24]
IM3.1.0 版本怎么集成CallSDK？官方文档里面没有相关描述。希望得到相关集成方案

**Comment by xkazer** [comment]
CallSDK是基于不iLiveSDK的，iLiveSDK暂未集成IMSDK 3.x版本

**Comment by edison-xiao** [comment]
那就目前来看IMSDK 3.x版本，要使用CallSDK音视频是实现不了了。什么时候3.x会集成啊
