### ISSUE TITLE
sdk有心跳包监听么？

### ISSUE THREAD

**Issue by songwj1989** [zhaoyang21cn/CallSDK_Android_Demo#25]
目前接通后可已根据MemberEvent来判断是否对方已不在线（无网络或直接杀掉进程）。但未接通的情况该怎么判断呢？比如呼叫方呼叫后直接杀掉进程，接收方一直停留在“拒绝/接受”的界面，只能接收方自己手动点击“拒绝”来停止

**Comment by xkazer** [comment]
sdk无法判断对方是否在线，但是呼叫是可以设置超时时间的

**Comment by songwj1989** [comment]
超时我知道啊，我的意思是：呼叫方呼叫后，接受方也接到了通知，但是不接通，这时呼叫方直接杀掉了进程，接受方App就一直等待接受方拒绝或接通了，但此时呼叫方App进程已经kill了

**Comment by ShengjieGeng** [comment]
既然设置了超时时间，即使呼叫方突然杀掉进程，那么到时间后也应该自动挂断的啊

**Comment by ShengjieGeng** [comment]
通话过程中某一方突然杀掉进程，MemberEvent能监听的到？？？

**Comment by xkazer** [comment]
可以通过心跳在业务层做处理

**Comment by songwj1989** [comment]
@ShengjieGeng 接通后，MemberEvent是可以监听到的；接通前是无法获知的，这可能需要走自己的接口来做心跳处理了。
