### ISSUE TITLE
初始化对方视图为大屏，自己为小屏失败

### ISSUE THREAD

**Issue by songwj1989** [zhaoyang21cn/CallSDK_Android_Demo#26]
呼叫方是可以的，接收方不行：
public void onCallEstablish(int callId) ｛
。。。
        avRootView.swapVideoView(0, 1);
        // 设置点击小屏切换及可拖动
        for (int i=1; i<ILiveConstants.MAX_AV_VIDEO_NUM; i++){
            final int index = i;
            AVVideoView minorView = avRootView.getViewByIndex(i);
            if (ILiveLoginManager.getInstance().getMyUserId().equals(minorView.getIdentifier())){
                minorView.setMirror(true);      // 本地镜像
            }
            minorView.setDragable(true);    // 小屏可拖动
            minorView.setGestureListener(new GestureDetector.SimpleOnGestureListener(){
                @Override
                public boolean onSingleTapConfirmed(MotionEvent e) {
                    avRootView.swapVideoView(0, index);     // 与大屏交换
                    return false;
                }
            });
        }
。。。
｝

另外，setSubCreatedListener监听无返回
        avRootView.setSubCreatedListener(new AVRootView.onSubViewCreatedListener() {
            @Override
            public void onSubViewCreated() {
                Log.e(TAG, "onSubViewCreated()");
//                avRootView.swapVideoView(0, 1);
            }
        });

**Comment by xkazer** [comment]
初始化对方为大屏，自己为小屏，可以直接在setSubCreatedListener中通过bindIdAndView将对方绑定到大屏，自己绑定到小屏

**Comment by songwj1989** [comment]
setSubCreatedListener监听无返回
avRootView.setSubCreatedListener(new AVRootView.onSubViewCreatedListener() {
@override
public void onSubViewCreated() {
Log.e(TAG, "onSubViewCreated()");
// avRootView.swapVideoView(0, 1);
}
});

**Comment by xkazer** [comment]
这个是小屏初始化回调，如果在onCreated中设置，肯定会进，如果进了房间才设置，不会再进的(已经初始化过了)
