### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#29]
Process: com.android.reeman, PID: 3334
   java.lang.NoClassDefFoundError: tencent.tls.platform.TLSLoginHelper
at com.tencent.ilivesdk.tlsmodule.TlsBusiness.init(TlsBusiness.java:35)
 at com.tencent.ilivesdk.ILiveSDK.initSdk(ILiveSDK.java:75)
当我集成了callsdk后，然后进行编译，老是报错，首先是我用的greenDAO报错，错误是找不到standardDatabase，然后还有我的OKhttp也会出现这样的问题NoClassDefFoundError.
![e cz s r x_9 dna8n](https://user-images.githubusercontent.com/18364968/28066302-074e5e9c-666f-11e7-9783-36003886c696.png)
![o40pp1w l89zxj abk5if4l](https://user-images.githubusercontent.com/18364968/28066303-076f9b66-666f-11e7-8e71-22393e9285d5.jpg)
![timz9is oguhc0dr0 l p](https://user-images.githubusercontent.com/18364968/28066304-077a5d4e-666f-11e7-94f2-778dd164ec1a.png)

**Comment by ShengjieGeng** [comment]
会不会跟手机架构有关

**Comment by xkazer** [comment]
找不到的都是jar中的类，可以看看是否是多dex问题:
https://github.com/casidiablo/multidex

**Comment by ShengjieGeng** [comment]
是这个问题，已经解决了。多谢大神
