### ISSUE TITLE
云通信的语音消息异常

### ISSUE THREAD

**Issue by songwj1989** [zhaoyang21cn/CallSDK_Android_Demo#3]
接入sdk后，云通信语音消息异常，具体表现在获取语音实体时奔溃，即TIMSoundElum.getSound()调用立即奔溃，且无exception。这里该如何解决

**Comment by xkazer** [comment]
callsdk基于ilivesdk，ilivesdk内部集成了IM，之前有接入imsdk的话，可将原集成去掉(无需另外初始化，登录imsdk)，看看是否为这里的冲突

**Comment by songwj1989** [comment]
下面的禁止上报什么的都不要么？

       // 设置log等级：为了提升性能可以设置为TIMLogLevel.values()[OFF.ordinal()，不打印log输出
        TIMManager.getInstance().setLogLevel(TIMLogLevel.OFF);
        // 禁止服务器自动代替上报已读
        TIMManager.getInstance().disableAutoReport();
        // 禁用crash上报
        TIMManager.getInstance().disableCrashReport();
        // 禁用消息存储
        // TIMManager.getInstance().disableStorage();
        // 初始化imsdk
        // TIMManager.getInstance().init(App.getIns());
        // 初始化直播sdk：因为直播sdk会初始化聊天，这里不再初始化聊天sdk了
        ILiveSDK.getInstance().initSdk(App.getIns(),
                TIMConfig.IM_APP_ID,
                TIMConfig.ACCOUNT_TYPE);

**Comment by xkazer** [comment]
配置可以要，TIMManager.getInstance().init这句不需要了，TIMManager.getInstance().login也不需要了

**Comment by songwj1989** [comment]
这个我已经是Ilive。login和logout了。我把crash上报开起来后，有exception了：
12-19 15:55:03.805 5746-6511/com.boyibo.xiuqu E/CrashReport: # EXCEPTION STACK:
                                                                       #00  pc 000c03d6 /data/app/com.boyibo.xiuqu-2/lib/arm/lib_imcore_jni_gyp.so [armeabi-v7a::]
                                                                      #01  pc 0008b76f /data/app/com.boyibo.xiuqu-2/lib/arm/lib_imcore_jni_gyp.so (Java_com_tencent_imcore_internalJNI_IMCoreUser_1applyDownloadFile +58) [armeabi-v7a::]
                                                                      #02  pc 007a5bf5 /data/dalvik-cache/arm/data@app@com.boyibo.xiuqu-2@base.apk@classes.dex
                                                             java:
                                                             com.tencent.imcore.IMCoreUser.applyDownloadFile(Unknown Source)
                                                             com.tencent.TIMSoundElem.getSound(Unknown Source)
                                                             com.boyibo.tencent.imessage.adapter.ChatMessageListAdapter$VoiceItemOnClickListener.onClick(ChatMessageListAdapter.java:1294)
                                                             android.view.View.performClick(View.java:5155)
                                                             android.view.View$PerformClick.run(View.java:20747)
                                                             android.os.Handler.handleCallback(Handler.java:739)
                                                             android.os.Handler.dispatchMessage(Handler.java:95)
                                                             android.os.Looper.loop(Looper.java:145)
                                                             android.app.ActivityThread.main(ActivityThread.java:5835)
                                                             java.lang.reflect.Method.invoke(Native Method)
                                                             java.lang.reflect.Method.invoke(Method.java:372)
                                                             com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                             com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
12-19 15:55:03.805 5746-6511/com.boyibo.xiuqu E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by songwj1989** [comment]
因为ILive的so说是只支持armeabi的，所以加了编译只编译了armeabi的so。
ndk{
            abiFilter 'armeabi'
        }

**Comment by xkazer** [comment]
目前只支持armeabi架构，所以请删掉非armeabi的目录，或加上只编译armeabi的配置，从上面的Crash上看，配置应没生效

**Comment by songwj1989** [comment]
那我再把armeabi的目录给删掉试试看

**Comment by songwj1989** [comment]
还是一样的，这要怎么做呢

**Comment by xkazer** [comment]
这里应该是工程保留了和iLiveSDK内置imsdk版本不一致的so，导致运行异常

**Comment by songwj1989** [comment]
那我要把so库删掉吗？

**Comment by songwj1989** [comment]
我看demo里面并没有这些so？

**Comment by xkazer** [comment]
全部删掉吧，android studio下载的aar里面有这些so的

**Comment by songwj1989** [comment]
包括万象优图的so？

**Comment by xkazer** [comment]
万象的不能删，ilivesdk只包含了imsdk和avsdk的相关文件

**Comment by songwj1989** [comment]
嗯，我已经调好了。感谢你的解答
