### ISSUE TITLE
偶尔会出现NoClassDefFoundError

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#31]
上次解决那个多dex的问题后，最近在调试时，偶尔会出现这个问题，会不会是程序退出时没有销毁那个类，导致了下次启动时失败。然后出现了sdk not initialized
![ouwk3 dqh1481x_uxon8ivv](https://user-images.githubusercontent.com/18364968/28163142-71073884-67fc-11e7-90c1-6dce6529937a.png)

**Comment by xkazer** [comment]
如果多dex已确认解决，可以考虑是混淆问题

**Comment by ShengjieGeng** [comment]
我没用到混淆

**Comment by ShengjieGeng** [comment]
需要添加吗？

**Comment by xkazer** [comment]
如果有添加混淆的话，需要按文档指示添加配置，如果没有的话，可以考虑是调试时引起，如果实际中没有出现，可以再观察下
