### ISSUE TITLE
视频通话失败

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#32]
最近手机测试时，有时候监听不到来电，但是可以打过去。有一种情况就是重新启动手机后就可以接收到来电。我用的ILVCallManager.addIncomingListener的监听。我有些地方用到了TIMMessageListener，这个listener会不会阻断ILVCallManager.addIncomingListener的监听啊？？他们有冲突吗？？

**Comment by ShengjieGeng** [comment]
我刚刚测试了把TIMMessageListener的监听取消。然后好像就没什么问题。这怎么办？我想两个都用

**Comment by ZhiruiLi** [comment]
Call SDK 内部使用了 IM SDK 接收信令，而 IM SDK 的 listener 只有一个，所以一旦设定了 TIMMessageListener，Call SDK 就无法接收消息了。Call SDK 提供了接收自定义消息的接口，具体可以参考 [API 文档](https://zhaoyang21cn.github.io/iLiveSDK_Help/callsdk/) 中的 `ILVCallConfig` 里的 `ILVCallConfig setCallMessageListener(TIMMessageListener)` 方法。当 Call SDK 接收到非内部消息时会回调该 listener 来处理消息。
