### ISSUE TITLE
so库在哪里下载

### ISSUE THREAD

**Issue by wangcc0909** [zhaoyang21cn/CallSDK_Android_Demo#33]
我需要so库下载来集成callSDK

**Comment by ZhiruiLi** [comment]
Call SDK 基于 ILive SDK 封装，Call SDK 本身的代码是纯 Java 的，如果需要 ILive SDK 相关的 so 库可以到 [这里](https://www.qcloud.com/document/product/268/7658) 找到。另外只需要按照 [Call SDK demo](https://github.com/zhaoyang21cn/CallSDK_Android_Demo) 页面上的方式添加 gradle 依赖即可，不需要自己下载 so 库。
