### ISSUE TITLE
视频通话endCall之后，本次通话创建的IM群组会被销毁么？

### ISSUE THREAD

**Issue by songwj1989** [zhaoyang21cn/CallSDK_Android_Demo#34]
视频通话成功后，IM群组被创建，但退出通话（双方都执行了endCall）群组未被销毁。是做什么限制了吗？

**Comment by xkazer** [comment]
默认是私有群组(Private)，私有群组是无法销毁的，需要等后台回收

**Comment by xkazer** [comment]
呼叫信令走的是IMSDK的消息，呼叫时，可以在option通过setOnlineCall配置是否使用在线消息，如果使用在线消息发起呼叫，未登录的一方就不会收到
