### ISSUE TITLE
剥离音视频和IM

### ISSUE THREAD

**Issue by SaberMaycry** [zhaoyang21cn/CallSDK_Android_Demo#36]
比我，项目用最新的IM3.1，但是想要集成iLive，但是iLive自带了2.5的IM；
请问，能提供单纯的iLiveSDK，或者gradle引用么！

**Comment by ZhiruiLi** [comment]
这个暂时不支持，因为 iLive 自身需要用到 IM SDK 2.x 来进行通讯
