### ISSUE TITLE
callsdk 配置

### ISSUE THREAD

**Issue by smiletolive** [zhaoyang21cn/CallSDK_Android_Demo#38]
compile 'com.tencent.callsdk:callsdk:1.0.16'
用这个配置更新没有更新到sdk，提示：
Error:(24, 13) Failed to resolve: com.tencent.callsdk:callsdk:1.0.16

**Comment by xkazer** [comment]
可以参考https://github.com/zhaoyang21cn/CallSDK_Android_Demo/issues/39
