### ISSUE TITLE
callsdk编译失败

### ISSUE THREAD

**Issue by iyfeng** [zhaoyang21cn/CallSDK_Android_Demo#39]
Error:(146, 13) Failed to resolve: com.tencent.callsdk:callsdk:1.0.23

**Comment by xkazer** [comment]
jcenter上是已经发布了[1.0.23](https://bintray.com/ilive/maven/callsdk/1.0.23#files/com%2Ftencent%2Fcallsdk%2Fcallsdk%2F1.0.23)的，可以用gradlew --info
定位下具体原因

**Comment by rx9158** [comment]
今天碰到相同问题，无法更新到sdk　　版本：1.0.21.  有些电脑上可以，　有些电脑上不行。

**Comment by iyfeng** [comment]
执行--info发现如下信息
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/tencent/callsdk/callsdk/1.0.23/callsdk-1.0.23.pom]
Resource missing. [HTTP HEAD: https://jcenter.bintray.com/com/tencent/callsdk/callsdk/1.0.23/callsdk-1.0.23.jar]
Resource missing. [HTTP GET: https://jitpack.io/com/tencent/callsdk/callsdk/1.0.23/callsdk-1.0.23.pom]
Resource missing. [HTTP HEAD: https://jitpack.io/com/tencent/callsdk/callsdk/1.0.23/callsdk-1.0.23.jar]

**Comment by wlianghe00** [comment]
@xkazer  jcenter上面移除了callSdk吗
![image](https://user-images.githubusercontent.com/3353880/28511372-7d06c54c-707f-11e7-867a-e4a16516fe73.png)

**Comment by xkazer** [comment]
抱歉，JCenter审核过期了，已经重新提交审核，预计明天可以恢复正常
