### ISSUE TITLE
初始化配置视频效果

### ISSUE THREAD

**Issue by songwj1989** [zhaoyang21cn/CallSDK_Android_Demo#4]
是否可以初始就可以配置美颜度、白化度、呼叫方和接受方的窗口？onCallEstablish()后配置了美颜度，好像没效果

**Comment by xkazer** [comment]
美颜美白只能在自己摄像头开启后配置，而且只对自己有效果。
初始化时配置呼叫方和接收方的窗口可以在onCreate中配置setSubCreatedListener，并在回调中配置

**Comment by songwj1989** [comment]
大概多久可以设置美艳美白呢？因为呼叫结束后才开启视频的，有相关的回调么？

**Comment by xkazer** [comment]
可以ILVBCallMemberListener中的onCameraEvent事件中判断出是自己开摄像头事件时设置

**Comment by songwj1989** [comment]
好的。那这个setSubCreatedListener监听是什么调用的?ILVCallManager?

**Comment by xkazer** [comment]
这个是AVRootView的方法，可以在onCreate时就调用

**Comment by songwj1989** [comment]
好的，谢谢
