### ISSUE TITLE
监听通话质量

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#40]
callsdk有这个方法吗

**Comment by xkazer** [comment]
可以参考 https://github.com/zhaoyang21cn/iLiveSDK_Android_Suixinbo/blob/master/doc/ILiveSDK/quality.md

**Comment by ShengjieGeng** [comment]
我在onCallEstablished方法调用的
if(ILiveRoomManager.getInstance() != null){
     ILiveQualityData qualityData = ILiveRoomManager.getInstance().getQualityData();
        if (qualityData != null) {
            System.out.println("qualityData=" + qualityData);
        }
}似乎没有用

**Comment by xkazer** [comment]
这个数据是实时更新的，建议定时去获取，onCallEstablish时获取数据可能都是0

**Comment by ShengjieGeng** [comment]
电话创建后我启动了一个timer，每隔三秒执行一次。执行此方法，可是if语句并不执行

**Comment by xkazer** [comment]
第一个if是常量获取，不会能为false，第二个if在进房间后应该是不会为空的，Android studio的话可以单步跟进去看下

**Comment by xkazer** [comment]
自测是没问题的

**Comment by ShengjieGeng** [comment]
获取前需要先调用ILiveRoomManager.getInstance().init()和ILiveRoomManager.getInstance().initAvRootView()吗？

**Comment by ShengjieGeng** [comment]
这是跟踪日志
![qq 20171108090726](https://user-images.githubusercontent.com/18364968/32526484-6f8db3e2-c464-11e7-959a-9b03281e6a34.jpg)

**Comment by xkazer** [comment]
[随心播](https://github.com/zhaoyang21cn/ILiveSDK_Android_Suixinbo)里有应用示例，参考一下吧
