### ISSUE TITLE
明明接通了电话，但是memberListener还是能监听到对方退出

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#44]
![2](https://user-images.githubusercontent.com/18364968/28856826-bb26c792-7777-11e7-8011-24503e56cdf5.png)

![1](https://user-images.githubusercontent.com/18364968/28856819-b1940186-7777-11e7-8e36-b934cfdaed9e.png)
![Uploading 2.png…]()

**Comment by ShengjieGeng** [comment]
好像是在设置的超时时间后会收到这个退出事件

**Comment by xkazer** [comment]
成员进出事件目前是由心跳维护，新版本中已废弃成员状态维护
