### ISSUE TITLE
callsdk接通后是会自动打开摄像头吗？能不能控制？

### ISSUE THREAD

**Issue by smiletolive** [zhaoyang21cn/CallSDK_Android_Demo#46]
我在初始化的时候调用了
ILVCallManager.getInstance().enableCamera(mCurCameraId, false);
mAvRootView.closeUserView(ILiveLoginManager.getInstance().getMyUserId(), AVView.VIDEO_SRC_TYPE_CAMERA, true);
但是接通后摄像头是打开的，而且我在接通回调onCallEstablish方法里面设置关闭不做延迟是无效的，延迟500ms就有效是什么原因呢？和视频小窗初始化有关吗？

**Comment by xkazer** [comment]
呼叫接口makeCall和接听接口acceptCall的option参数可以配置是否开启摄像头，麦克风等

**Comment by smiletolive** [comment]
好的，谢谢
