### ISSUE TITLE
CallSDK支持多路流单独输出吗？

### ISSUE THREAD

**Issue by jerrylining** [zhaoyang21cn/CallSDK_Android_Demo#5]
我们想要互动直播的每一路的输入流最后输出的时候能进行单独输出

**Comment by xkazer** [comment]
能将需求描述清晰一点吗？
主播的输入，本地数据预览的输出？
还是观众，远程数据预览的输出？
还是说，想不同视频渲染到不同的控件上？

**Comment by jerrylining** [comment]
远端输出到观看端

发自我的 iPhone

**Comment by jerrylining** [comment]
我想要的效果是互动端的每一路流能够单独输出 你们现在的机制应该是互动端的视频混合输出吧？

发自我的 iPhone

**Comment by xkazer** [comment]
单独输出的，每一路视频流，都可以独立控制(渲染，放大，旋转等)

**Comment by jerrylining** [comment]
能设置观看流地址吗？


发自我的 iPhone

**Comment by jerrylining** [comment]
兄弟 昨天下午发的能回一下吗？

发自我的 iPhone

**Comment by xkazer** [comment]
互动直播内部用的是私有协议，只能用互动直播的客户端观看。
但是主播是支持旁路推流的，开启旁路推流，开启后，可以通过你说的观看地址观看
https://www.qcloud.com/document/product/268/7612:

**Comment by jerrylining** [comment]
那有办法获取观看地址吗？

发自我的 iPhone

**Comment by jerrylining** [comment]
因为现在需要的就是这种连麦互动 并且能获知观看地址

发自我的 iPhone

**Comment by xkazer** [comment]
上面已经答复过了，每一个主播(包括上麦观众)，开启旁推流，就有观看地址了

**Comment by jerrylining** [comment]
每次生成的播放地址都不一样 而且获取的地址去播放 播放测试的时候没流媒体数据

发自我的 iPhone

**Comment by xkazer** [comment]
可以在云后台直播系统配置，如果是直播码模式的话，可以保证播放地址生成一致，这个是实时直播，有在直播，就能看到
