### ISSUE TITLE
华为mate8couldn't find "libqalcodecwrapper.so"

### ISSUE THREAD

**Issue by bravekingzhang** [zhaoyang21cn/CallSDK_Android_Demo#52]
couldn't find "libqalcodecwrapper.so"

couldn't find "libqalcodecwrapper.so"

couldn't find "libqalcodecwrapper.so"

**Comment by xkazer** [comment]
iLiveSDK是包含armeabi和armeabi-v7a两种架构下的这个so的，检查是否采用其它架构

**Comment by bravekingzhang** [comment]
multidex 兼容性问题考虑了没？ @xkazer

**Comment by xkazer** [comment]
多dex可以参考[https://github.com/casidiablo/multidex](https://github.com/casidiablo/multidex)

**Comment by bravekingzhang** [comment]
问题已经解决：
是这个 
如果之前ndk配置这个的话，改为下面的
 //abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'x86'
 abiFilters 'armeabi', 'armeabi-v7a'

因为 iLiveSDK是只包含armeabi和armeabi-v7a两种架构下的so的
