### ISSUE TITLE
ILVIncomingListener的onNewIncoming会打出很多log

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#54]
就是每当接收到来电信息后，我在这里打一条log，但是不清楚为什么打出很多条，好像调用了多次一样，这跟网络有关吗？或者是由于多次调用了ILVCallManager.getInstance().addIncomingListener(incomingListener)这个方法？求指教，谢谢！
![qq 20170912170726](https://user-images.githubusercontent.com/18364968/30317737-92e2356a-97dd-11e7-90ef-aa0e83769621.jpg)

**Comment by xkazer** [comment]
应该是由于多次调用addIncomingListener引起，添加后需要用removeIncomingListener来移除
