### ISSUE TITLE
不会自动打开前置摄像头

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#55]
来电话后接听总是不会自动打开前置摄像头，求解。（我现在的解决办法就是启动一个子线程两次调用switchcamera（）方法，这样才能打开摄像头）

**Comment by ShengjieGeng** [comment]
设置了autoCamera（true）

**Comment by xkazer** [comment]
autoCamera是自动打开摄像头，另有一个方法cameraId来指定打开的摄像头id
