### ISSUE TITLE
挂电话报空指针异常

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#56]
我抓了一下log,求解，谢谢
![qq 20170919101509](https://user-images.githubusercontent.com/18364968/30573002-dcd71b2c-9d23-11e7-971a-08a38cf7cc65.jpg)

**Comment by ShengjieGeng** [comment]
if (ILVCallManager.getInstance()!=null)我用这个过滤能行吗

**Comment by xkazer** [comment]
上层调用的sendGroupMessage接口？getInstance()这个静态方法可以看下实现，不会返回null的啊，应该为结束通话后心跳未停止，能否提供完整iLiveSDK日志给我看下？可以发我邮箱xkazer@qq.com

**Comment by ShengjieGeng** [comment]
这个出现的次数不多，我只是执行了ILVCallManager.getInstance().endCall(callID)后接着调用ILVCallManager.getInstance().shutdown()

**Comment by xkazer** [comment]
额，shutdown这个是还是有些问题，endcall结束呼叫是个异常操作，shutdown还是需要等操作完成，上抛onCallEnd后再调用吧

**Comment by ShengjieGeng** [comment]
我已经改了，我改执行ILVCallManager.getInstance().ondestroy后调用它
