### ISSUE TITLE
AVRootView更改背景

### ISSUE THREAD

**Issue by deyunvip** [zhaoyang21cn/CallSDK_Android_Demo#6]
AVRootView可以更改背景吗？并且其它视频窗口缩小仍然可以看到背景，谢谢

**Comment by xkazer** [comment]
AVRootView不支持更改背景，AVVideoView可以设置背景

**Comment by LelandLi** [comment]
在通话过程中关闭摄像头，界面显示的是最后一帧的界面，怎么设置成黑色的
