### ISSUE TITLE
ILVCallManager.getInstance().makeCall有时报空指针异常

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#64]
![error](https://user-images.githubusercontent.com/18364968/32257541-9e8dbff8-bef0-11e7-94fb-fb42d14c3ca7.jpg)
在调用makeCall之前调用过addCallListener（没有报空指针异常）。求解，谢谢

**Comment by xkazer** [comment]
使用前调用ILVCallManager.getInstance().init进行初始化
