### ISSUE TITLE
视频画面旋转90度

### ISSUE THREAD

**Issue by Quxianshan** [zhaoyang21cn/CallSDK_Android_Demo#7]
双方本地预览是正的, 但对方看到自己的画面都是旋转了的; 应用默认处于横屏状态, 搜了下api 没有设置这个的接口, 请问如何解决?

**Comment by xkazer** [comment]
可参考[旋转设置文档](https://github.com/zhaoyang21cn/suixinbo_doc/blob/master/doc2/rotate.md)

**Comment by Quxianshan** [comment]
现在本地升级到'com.tencent.callsdk:callsdk:1.0.8' 版本, 按照 旋转设置文档 的方案二方法, 设置主播不旋屏,  设置方法如下:
// 设置点击小屏切换及可拖动
        for (int i=1; i<ILiveConstants.MAX_AV_VIDEO_NUM; i++){
            final int index = i;
            AVVideoView minorView = avRootView.getViewByIndex(i);
            if (ILiveLoginManager.getInstance().getMyUserId().equals(minorView.getIdentifier())){
                minorView.setMirror(true);      // 本地镜像
            }
            minorView.setDragable(true);    // 小屏可拖动
            minorView.setRotate(false);
            minorView.setDiffDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
            minorView.setSameDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
            minorView.setGestureListener(new GestureDetector.SimpleOnGestureListener(){
                @Override
                public boolean onSingleTapConfirmed(MotionEvent e) {
                    avRootView.swapVideoView(0, index);     // 与大屏交换
                    return false;
                }
            });
        }
最终显示的是, 双方本地预览正常, 对方画面180度倒立, 是我哪里设置的不对么?

**Comment by Quxianshan** [comment]
Hi

现在本地升级到'com.tencent.callsdk:callsdk:1.0.8' 版本, 按照 旋转设置文档 的方案二方法, 设置主播不旋屏, 设置方法如下:
// 设置点击小屏切换及可拖动
for (int i=1; i<ILiveConstants.MAX_AV_VIDEO_NUM; i++){
final int index = i;
AVVideoView minorView = avRootView.getViewByIndex(i);
if (ILiveLoginManager.getInstance().getMyUserId().equals(minorView.getIdentifier())){
minorView.setMirror(true); // 本地镜像
}
minorView.setDragable(true); // 小屏可拖动
minorView.setRotate(false);
minorView.setDiffDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
minorView.setSameDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
minorView.setGestureListener(new GestureDetector.SimpleOnGestureListener(){
@Override<https://github.com/Override>
public boolean onSingleTapConfirmed(MotionEvent e) {
avRootView.swapVideoView(0, index); // 与大屏交换
return false;
}
});
}
最终显示的是, 双方本地预览正常, 对方画面大屏显示180度倒立, 切换本地预览到大屏, 对方画面在小屏显示, 画面旋转90度 是我哪里设置的不对么?

________________________________
qu.xianshan@live.com

发件人： xkazer<mailto:notifications@github.com>
发送时间： 2017-01-20 10:32
收件人： zhaoyang21cn/CallSDK_Android_Demo<mailto:CallSDK_Android_Demo@noreply.github.com>
抄送： Quxianshan<mailto:qu.xianshan@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [zhaoyang21cn/CallSDK_Android_Demo] 视频画面旋转90度 (#7)

可参考旋转设置文档<https://github.com/zhaoyang21cn/suixinbo_doc/blob/master/doc2/rotate.md>

**Comment by Quxianshan** [comment]
Hi

现在本地升级到'com.tencent.callsdk:callsdk:1.0.8' 版本, 按照 旋转设置文档 的方案二方法, 设置主播不旋屏, 设置方法如下:
// 设置点击小屏切换及可拖动
for (int i=1; i<ILiveConstants.MAX_AV_VIDEO_NUM; i++){
final int index = i;
AVVideoView minorView = avRootView.getViewByIndex(i);
if (ILiveLoginManager.getInstance().getMyUserId().equals(minorView.getIdentifier())){
minorView.setMirror(true); // 本地镜像
}
minorView.setDragable(true); // 小屏可拖动
minorView.setRotate(false);
minorView.setDiffDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
minorView.setSameDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
minorView.setGestureListener(new GestureDetector.SimpleOnGestureListener(){
@Override<https://github.com/Override>
public boolean onSingleTapConfirmed(MotionEvent e) {
avRootView.swapVideoView(0, index); // 与大屏交换
return false;
}
});
}
最终显示的是, 双方本地预览正常, 对方画面大屏显示180度倒立, 切换本地预览到大屏, 对方画面在小屏显示, 画面旋转90度 是我哪里设置的不对么?

**Comment by JasonXiao001** [comment]
横屏下，只能保证主播自己画面始终是正的，远端画面只有一个方向是正的，需要旋转手机到正向的

**Comment by Quxianshan** [comment]
现在是用的互动直播当作视频通话来实现, 有一方是固定在净水机上, 无法调整屏幕方向 默认就是横屏, 现在的情况是只有双方自己的预览是正的, 对方看到的画面都是旋转的, 在大屏显示就是旋转180度倒立, 在小屏就旋转90度.

**Comment by JasonXiao001** [comment]
横屏的时候视频目前做了向一个方向的旋转，所以需要把观众手机旋转180,把视频转正，由于主播自己始终是好的，所以这个时候就可以两个都是正向画面了

**Comment by Quxianshan** [comment]
主播是的是呼叫方还是被叫方? 如果A呼叫B, A是主播, B是观众, 那需要旋转B的手机180度, 如果B呼叫A, A变成了观众, B是主播, 那需要旋转A 180度 是这样么? 主要手机端旋转好弄, 另外一端是固定的机器, 方向是没法旋转的 有别的解决方案么? 比如AB双方, 让B固定是主播, 不管是A呼叫B 还是B呼叫A, 都是让B去创建房间, 邀请A加入房间?

**Comment by JasonXiao001** [comment]
你可以先把rotate设置为true

**Comment by Quxianshan** [comment]
现在AB两端都设置成为:
for (int i=1; i<ILiveConstants.MAX_AV_VIDEO_NUM; i++){
            final int index = i;
            AVVideoView minorView = avRootView.getViewByIndex(i);
            if (ILiveLoginManager.getInstance().getMyUserId().equals(minorView.getIdentifier())){
                minorView.setMirror(true);      // 本地镜像
            }
            minorView.setDragable(true);    // 小屏可拖动
            minorView.setRotate(true);
            minorView.setSameDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
            minorView.setDiffDirectionRenderMode(AVVideoView.ILiveRenderMode.SCALE_TO_FIT);
            minorView.setGestureListener(new GestureDetector.SimpleOnGestureListener(){
                @Override
                public boolean onSingleTapConfirmed(MotionEvent e) {
                    avRootView.swapVideoView(0, index);     // 与大屏交换
                    return false;
                }
            });
        }
现在不管A呼叫B 还是B呼叫A, 在B固定不动的情况下, 旋转A是可以让画面正常显示的. 只是手机端(A)的UI显示是反的 手动设置了Activity的方向, 倒立的时候UI可以调过来, 但是图像还是反的, 应该怎么去设置??

**Comment by JasonXiao001** [comment]
这个问题我们这边修改一下，这两天更新，更新后在这个issue里告知你，到时试试

**Comment by Quxianshan** [comment]
好的, 多谢大神.

**Comment by JasonXiao001** [comment]
把ilivesdk的版本改为1.2.2试一下
rotate设置为false

**Comment by Quxianshan** [comment]
AB两端都更新到1.2.2 rotate为false, 现在本地大屏显示 远端小屏显示 AB两端画面都是正常的, 如果切换大小屏, 本地小屏显示正常, 远端大屏显示画面旋转180度倒立.

**Comment by JasonXiao001** [comment]
这个不应该，对于程序来讲，大画面和小画面没有什么区别表现应该一致，请确认大画面也是设置的false。我们测试过这个情况，手机横屏，小画面也是横的，此时大画面和小画面表现是一致的

**Comment by Quxianshan** [comment]
找到原因了, 之前设置rotate的地方是在demo里面的onCallEstablish回调内的for循环内, 仔细看了代码发现, for循环的下标是从1开始的, 现在是在循环开始前给avRootView.getViewByIndex(0).setRotate(false);设置为false, 现在AB两端随意呼叫, 切换画面 显示均正常.
