### ISSUE TITLE
今天早上发现我们的集成项目视频通话页面旋转异常

### ISSUE THREAD

**Issue by ShengjieGeng** [zhaoyang21cn/CallSDK_Android_Demo#72]
今天早上发现我们的集成项目视频通话页面旋转异常，以前好好的。就是今天突然这样了。旋转了180度

**Comment by ShengjieGeng** [comment]
还请工程师排查下问题。谢谢

**Comment by xkazer** [comment]
默认情况下SDK是会监听重力感应，根据当前屏幕自定义旋转的(sdk已适配支持常规手机、平板等)
针对非常规机型，可以使用AVRootView的纠正接口对角度进行纠正:
setLocalRotationFix(主播端纠正本地自己的角度)、setRemoteRotationFix(主播端纠正远端自己的角度)
而对于实际不会旋转的设备，推荐是直接关闭sdk的旋转机制:
setAutoOrientation配置为false
并通过setDeviceRotation配置设备角度

**Comment by ShengjieGeng** [comment]
我用的是callsdk:1.0.17，还没更新到最新的

**Comment by ShengjieGeng** [comment]
我之前就是把方向写死的。然后对方传过来的画面直接旋转了180

**Comment by xkazer** [comment]
上面的接口是iLiveSDK的，CallSDK是负责业务封装，不涉及渲染

**Comment by ShengjieGeng** [comment]
好的，谢谢
