### ISSUE TITLE
发起视频通话，对方收不到请求

### ISSUE THREAD

**Issue by wenjian1314** [zhaoyang21cn/CallSDK_Android_Demo#8]
之前还是可以的，今天突然就不行了，发送方使用ILVCallManager.getInstance().makeCall(selectUser, option1);返回的是正确的callId， 接受方设置了incominglistener的回调，但是发送方发送请求后接收方并没有调用onNewIncomingCall。
双方都保持登录状态

**Comment by wenjian1314** [comment]
另外，我还使用了coversation.sendMessage发送文本消息，然而接收方也没有收到TIMMessageListener的onNewMessages的回调

**Comment by xkazer** [comment]
从描述上看，是接收方无法收到IM消息，这里需要排除被下线的可能性，可以反过来用接收方呼叫或发消息给主叫，看看现象

**Comment by wenjian1314** [comment]
我双方都发送了请求，但是都收不到

**Comment by xkazer** [comment]
双方都无法收到，就需要确认:
1、使用了不同的appid
2、IM未登录或没有初始化

可以参考demo的初始化，登录流程，根据关键日志定位下

**Comment by wenjian1314** [comment]
I/ILVBLogin: Key_Procedure|ILVB-iLiveLogin|login success
这行日志应该能表示我登录和初始化都没有问题吧，并且我也能获取自己和对方的资料

**Comment by xkazer** [comment]
这个只表示登录成功了，ILVCallManager的init有调用吧

**Comment by wenjian1314** [comment]
有的，都未显示异常

**Comment by xkazer** [comment]
@wenjian1314 请加入群594923937，我根据日志看下
