### ISSUE TITLE
callsdk和互动直播的冲突

### ISSUE THREAD

**Issue by android1166liang** [zhaoyang21cn/CallSDK_Android_Demo#80]
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by xkazer** [comment]
具体冲突问题要看具体日志，你上面的图中日志只是结论，冲突的地方没有发出来

callsdk本身就包含了互动直播，也就是说集成了callsdk，可以直接使用互动直播的所有接口

**Comment by android1166liang** [comment]
冲突时so文件的冲突

**Comment by xkazer** [comment]
参考前一条回复，callsdk本身就包含了互动直播，意思是集成了callsdk，就不要再另外集成互动直播
