### ISSUE TITLE
用户不在线状态下收到音视频请求。登录之后调用了onNewIncomingCall回调

### ISSUE THREAD

**Issue by chenyao994** [zhaoyang21cn/CallSDK_Android_Demo#86]
这是版本号
 compile 'com.tencent.ilivesdk:ilivesdk:1.8.3'
    compile 'com.tencent.callsdk:callsdk:1.0.30'

**Comment by xkazer** [comment]
没懂具体是个么问题。    

如果是使用的是普遍消息的呼叫，用户不在线时是可以收到离线推送的，可以参考[IMSDK消息推送](https://cloud.tencent.com/document/product/269/3899)

登录后也会收到来电消息的，来电是有时间戳可以判断的

**Comment by OvenCroc** [comment]
我也是遇到相同的问题 , A用户不在线的时候, B用户呼叫A用户,挂断之后, 登录A用户, A用户依然会执行onNewIncomingCall  , 大佬求帮助啊

**Comment by xkazer** [comment]
呼叫信令走的是IMSDK的消息，呼叫时，可以在option通过setOnlineCall配置是否使用在线消息，如果使用在线消息发起呼叫，未登录的一方就不会收到

**Comment by OvenCroc** [comment]
非常感谢你的回复 , 已经通过你说的方法解决问题了 , 再次感谢 @xkazer
